#!/bin/bash
#txbdown=true txbrename=true txbcptos3=true txbtrancode=true txbremoterm=true txblocalmv=true ./txbjob.sh test
localdir=/gochina/publicspace/src
bakdir=/gochina/publicspace/srcbak
s3dir=/mnt/s3/publicspace/videos/src
s3dir2=/mnt/s3/publicspace/videos/dst
s3bucket=ottcloud
bucksrc=publicspace/videos/src
buckdst=publicspace/videos/dst
txbtool=/gochina/gochina
logpath=/gochina/publicspace/log
datapath=/gochina/publicspace/data
thumbgap=10s

txbdown=true
txbrename=true
txbcptos3=true
txbtrancode=true
txbremoterm=true
txblocalmv=true


txbmapsrc[0]="cp"
txbmapdst[0]="cp"
txbmapsrc[1]="ad"
txbmapdst[1]="ad"
txbmapsrc[2]="clips"
txbmapdst[2]="clips"

videodstformat=mp4
mailrecvers=hejiayi@gochinatv.com,lisi@gochinatv.com,zhangyue@gochinatv.com,fengzhiwen@gochinatv.com,panxinming@gochinatv.com
mailrecverstest=hejiayi@gochinatv.com,lisi@gochinatv.com,zhangyue@gochinatv.com,fengzhiwen@gochinatv.com
