#!/bin/bash
#txbdown=true txbrename=true txbcptos3=true txbtrancode=true txbremoterm=true txblocalmv=true ./txbjob.sh test
localdir=/gochina/tuxiaobei/src
bakdir=/gochina/tuxiaobei/srcbak
s3dir=/mnt/s3/tuxiaobei/videos/src
s3dir2=/mnt/s3/tuxiaobei/videos/dst
s3bucket=ottcloud
bucksrc=tuxiaobei/videos/src
buckdst=tuxiaobei/videos/dst
txbtool=/gochina/gochina
logpath=/gochina/tuxiaobei/log
datapath=/gochina/tuxiaobei/data
thumbgap=10s

txbdown=true
txbrename=true
txbcptos3=true
txbtrancode=true
txbremoterm=true
txblocalmv=true


txbmapsrc[0]="故事"
txbmapdst[0]="story"
txbmapsrc[1]="古诗"
txbmapdst[1]="poem"
txbmapsrc[2]="英语"
txbmapdst[2]="english"
txbmapsrc[3]="三字经"
txbmapdst[3]="classic"
txbmapsrc[4]="十万"
txbmapdst[4]="education"
txbmapsrc[5]="儿歌"
txbmapdst[5]="song"


videodstformat=m3u8
mailrecvers=hejiayi@gochinatv.com,zhixueyong@gochinatv.com,caolei@gochinatv.com,janreyho@gmail.com
mailrecverstest=hejiayi@gochinatv.com
