#!/bin/bash
#txbdown=true txbrename=true txbcptos3=true txbtrancode=true txbremoterm=true txblocalmv=true ./txbjob.sh test
localdir=~/gochina/zhongguolan/src
bakdir=~/gochina/zhongguolan/srcbak
s3dir=/mnt/s3/zhongguolan/videos/src
s3bucket=ottcloud
bucksrc=zhongguolan/videos/src
buckdst=zhongguolan/videos/dst
txbtool=~/gochina/gochina
logpath=~/gochina/zhongguolan/log

txbdown=true
txbrename=true 
txbcptos3=true 
txbtrancode=true 
txbremoterm=true 
txblocalmv=true 


txbmapsrc[0]="故事"
txbmapdst[0]="story"
txbmapsrc[1]="古诗"
txbmapdst[1]="poem"
txbmapsrc[2]="英语"
txbmapdst[2]="english"
txbmapsrc[3]="三字经"
txbmapdst[3]="classic"
txbmapsrc[4]="十万"
txbmapdst[4]="education"
txbmapsrc[5]="儿歌"
txbmapdst[5]="song"
